using System.Text;
using System.Text.Encodings.Web;
using System.Text.Unicode;
using CloudSealed.ML.Engine.Models;

namespace CloudSealed.ML.Engine.Reporting;

// HTML autocontido (CSS inline, sem CDN) para demo/compartilhamento — não é
// um dashboard servido. Mesma paleta visual do relatório do JIT-Optimization-Engine
// para consistência de marca entre os dois motores.
public static class HtmlReportRenderer
{
    private static readonly Dictionary<string, string> SeverityColors = new()
    {
        ["LOW"] = "#6b7280",
        ["MEDIUM"] = "#d97706",
        ["HIGH"] = "#dc2626",
        ["CRITICAL"] = "#991b1b",
    };

    private const string Css = """
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; max-width: 900px;
               margin: 40px auto; padding: 0 20px; color: #1f2937; background: #fff; }
        h1 { font-size: 22px; } h2 { font-size: 16px; margin-top: 32px; color: #374151; }
        .summary { color: #4b5563; }
        .cards { display: flex; gap: 16px; margin: 20px 0; flex-wrap: wrap; }
        .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px; min-width: 140px; }
        .card .label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
        .card .value { font-size: 22px; font-weight: 600; }
        table { border-collapse: collapse; width: 100%; margin-top: 8px; }
        th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
        th { color: #6b7280; font-weight: 600; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; color: #fff; font-size: 11px; font-weight: 600; }
        footer { margin-top: 40px; color: #9ca3af; font-size: 12px; }
        """;

    public static string Render(PredictArchitectureResponse response, string companyName)
    {
        var title = string.IsNullOrWhiteSpace(companyName)
            ? "Predictive-ML-Core"
            : $"Predictive-ML-Core — {companyName}";

        var findingRows = new StringBuilder();
        var recommendationRows = new StringBuilder();
        foreach (var prediction in response.Predictions)
        {
            foreach (var finding in prediction.Findings)
            {
                var color = SeverityColors.GetValueOrDefault(finding.Severity, "#6b7280");
                findingRows.Append(
                    $"<tr><td>{Esc(prediction.SystemName)}</td>"
                    + $"<td><span class='badge' style='background:{color}'>{Esc(finding.Severity)}</span></td>"
                    + $"<td>{Esc(finding.Title)}</td><td>{Esc(finding.Description)}</td></tr>");
            }
            foreach (var recommendation in prediction.Recommendations)
            {
                recommendationRows.Append(
                    $"<tr><td>{Esc(prediction.SystemName)}</td><td>{Esc(recommendation.Title)}</td>"
                    + $"<td>{Esc(recommendation.Effort)}</td><td>{Esc(recommendation.Description)}</td></tr>");
            }
        }

        var findingsBody = findingRows.Length > 0 ? findingRows.ToString() : "<tr><td colspan=\"4\">None found.</td></tr>";
        var recommendationsBody = recommendationRows.Length > 0 ? recommendationRows.ToString() : "<tr><td colspan=\"4\">None.</td></tr>";

        return $"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <title>{Esc(title)}</title>
            <style>{Css}</style>
            </head>
            <body>
            <h1>{Esc(title)}</h1>
            <p class="summary">{Esc(response.ArchitectureSummary)}</p>
            <div class="cards">
              <div class="card"><div class="label">Overall score</div><div class="value">{response.OverallArchitectureScore}/100</div></div>
              <div class="card"><div class="label">Systems</div><div class="value">{response.Predictions.Count}</div></div>
              <div class="card"><div class="label">Findings</div><div class="value">{response.Predictions.Sum(p => p.Findings.Count)}</div></div>
            </div>
            <h2>Findings</h2>
            <table>
            <tr><th>System</th><th>Severity</th><th>Title</th><th>Description</th></tr>
            {findingsBody}
            </table>
            <h2>Recommendations</h2>
            <table>
            <tr><th>System</th><th>Title</th><th>Effort</th><th>Description</th></tr>
            {recommendationsBody}
            </table>
            <footer>Generated by <a href="https://github.com/cloudsealed/Predictive-ML-Core">Predictive-ML-Core</a>
            — deterministic, auditable rule scoring.</footer>
            </body>
            </html>
            """;
    }

    // UnicodeRanges.All keeps accented/UTF-8 text readable in the source
    // (matching cloudsealed_jit's report.py, which uses Python's html.escape)
    // while still escaping the characters that matter for XSS: &<>"'.
    private static readonly HtmlEncoder Encoder = HtmlEncoder.Create(UnicodeRanges.All);

    private static string Esc(string value) => Encoder.Encode(value);
}
