"""Post or update a pull-request comment with a predictive-ml-core report.

Stdlib-only (urllib) so the composite action needs no extra pip install.
Finds a previous comment by its hidden marker and edits it in place, so
re-runs on the same PR don't spam the thread. Mirrors
JIT-Optimization-Engine/scripts/post_pr_comment.py.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request

MARKER = "<!-- predictive-ml-core-report -->"


def _api(method: str, url: str, token: str, body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode()) if resp.length != 0 else {}


def render_markdown(report: dict) -> str:
    predictions = report["predictions"]
    finding_count = sum(len(p["findings"]) for p in predictions)

    lines = [
        MARKER,
        "## 🏗️ predictive-ml-core — architecture risk audit",
        "",
        report["architectureSummary"],
        "",
        f"| Overall score | Systems | Findings |",
        f"|---|---|---|",
        f"| **{report['overallArchitectureScore']}/100** | {len(predictions)} | {finding_count} |",
    ]

    findings_rows = [
        (p["systemName"], f) for p in predictions for f in p["findings"]
    ]
    if findings_rows:
        lines += ["", "### Findings", "", "| System | Severity | Title | |", "|---|---|---|---|"]
        for system_name, finding in findings_rows[:10]:
            lines.append(
                f"| {system_name} | {finding['severity']} | {finding['title']} | {finding['description']} |"
            )

    recommendation_rows = [
        (p["systemName"], r) for p in predictions for r in p["recommendations"]
    ]
    if recommendation_rows:
        lines += ["", "### Top recommendations", ""]
        for system_name, rec in recommendation_rows[:5]:
            lines.append(f"- **{rec['title']}** ({system_name}) — effort {rec['effort']}")

    lines += ["", "_Generated by [Predictive-ML-Core](https://github.com/cloudsealed/Predictive-ML-Core) "
                    "— deterministic, auditable rule scoring, method in "
                    "[METHODOLOGY.md](https://github.com/cloudsealed/Predictive-ML-Core/blob/main/METHODOLOGY.md)._"]
    return "\n".join(lines)


def main() -> int:
    token = os.environ["GITHUB_TOKEN"]
    report_path = os.environ["REPORT_JSON"]
    event_path = os.environ["GITHUB_EVENT_PATH"]
    repo = os.environ["GITHUB_REPOSITORY"]

    with open(event_path, encoding="utf-8") as f:
        event = json.load(f)
    pr_number = event.get("pull_request", {}).get("number")
    if pr_number is None:
        print("Not a pull_request event; skipping comment.")
        return 0

    with open(report_path, encoding="utf-8") as f:
        report = json.load(f)

    body = render_markdown(report)
    base = f"https://api.github.com/repos/{repo}"

    comments = _api("GET", f"{base}/issues/{pr_number}/comments?per_page=100", token)
    existing = next((c for c in comments if MARKER in c.get("body", "")), None)

    if existing:
        _api("PATCH", f"{base}/issues/comments/{existing['id']}", token, {"body": body})
        print(f"Updated comment {existing['id']} on PR #{pr_number}.")
    else:
        _api("POST", f"{base}/issues/{pr_number}/comments", token, {"body": body})
        print(f"Posted new comment on PR #{pr_number}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
